name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  myInput:              # change this
    description: 'input description here'
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
