name: run-aqa with openjdk artifact
on:
  push:
jobs:
  run-aqawindows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        build_list: [external]
    steps:
    - uses: actions/checkout@v1
    - uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: '11'
        architecture: x64
    - name: AQA
      uses: AdoptOpenJDK/run-aqa@v1
      with: 
        version: '11'
        jdksource: 'install-jdk'
        build_list: ${{ matrix.build_list }}
        target: '_sanity'