name: "place holder for example"
on:
  push:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] #[windows-2016, ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Cache BootJDK
      id: Cache-BootJDK
      uses: actions/cache@v2
      with:
        path: ~/BootJDK
        key: ${{ runner.os }}-BootJDK
        restore-keys: |
          ${{ runner.os }}-BootJDK
    - uses: sophia-guo/build-jdk@testCache
      id: buildJDK
      with: 
        javaToBuild: 'jdk14u'
