name: "place holder for example"
on:
  push:
    branches-ignore:
      - '**'
jobs:
  build:
    runs-on: macos-10.15 # ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      id: buildJDK
    - run: echo ${{ steps.buildJDK.outputs.BuildJDKDir }}