name: "run-aqa build with push to master"
on:
  push:


jobs:
  callsiteTest: # make sure build/ci work properly
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2016]
    steps:
    - uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: '8'
        targets: 'JDK_8'
#       impl: 'openj9'
        source: 'nightly'
#        source: 'https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk11u-2020-10-31-16-42/OpenJDK11U-jdk_x64_mac_openj9_2020-10-31-16-42.tar.gz'
#        sourceType: 'url'
#        archiveExtension: '.tar'
    - name: AQA
      uses: sophia-guo/run-aqa@depends
      with: 
        version: '8'
        jdksource: 'install-jdk'
        build_list: 'system/jlm'
        target: '_TestJlmRemoteMemoryNoAuth'
#    - name: AQA
#      uses: sophia-guo/run-aqa@depends
#      with: 
#        version: '8'
#        jdksource: 'install-jdk'
#        build_list: 'functional'
#        target: '_floatSanityTests'
#        openjdk_testRepo: 'sophia-guo/openjdk-tests:openj9'
#        openjdk_testRepo: 'sophia-guo/openjdk-tests:openj9'
    - name: upload ubuntu result
      uses: actions/upload-artifact@v2
      if: failure() && contains(matrix.os, 'ubuntu')
      with:
        name: test_output_callsite_ubuntu
        path: ./**/test_output_*/
    - name: upload mac result
      uses: actions/upload-artifact@v2
      if: failure() && contains(matrix.os, 'macos')
      with:
        name: test_output_callsite_macos
        path: ./**/test_output_*/