name: "place holder for example"
on:
  push:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2016, ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - run: printenv
    - uses: sophia-guo/runaqaTest@test2
    - run: printenv
