name: "build-jdk-openj9 with adoptopenjdk openjdk-build linux"
on: # rebuild any PRs and main branch changes
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, macos-10.15]
    steps:
    - uses: actions/checkout@v1
    - uses: sophia-guo/build-jdk-hotspot@gradle
      id: buildJDK
      with: 
        javaToBuild: 'jdk14u'
        impl: 'openj9'
    - run: ${{ steps.buildJDK.outputs.BuildJDKDir }}/bin/java -version
    - uses: actions/upload-artifact@v2-preview
      if: failure()
      with:
        name: configure_output
        path: ./**/config.log