name: "nightly build-jdk nightly"
on:
  push:

jobs:
  hotspot14:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, macos-10.15]
        impl: [hotspot, openj9]
        javaToBuild: [jdk11u, jdk15u]
    steps:
    - uses: actions/checkout@v2
    - uses: sophia-guo/build-jdk@buildfarm
      id: buildJDK
      with: 
        javaToBuild: ${{ matrix.javaToBuild }}
        impl: ${{ matrix.impl }}
    - run: ${{ steps.buildJDK.outputs.BuildJDKDir }}/bin/java -version
  
