name: "place holder for example"
on:
  push:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2016] #[ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Cache Cygwin
      id: cache-cygwin
      uses: actions/cache@v2
      if: contains(${{runner.os}}, 'windows')
      with:
        path: 'C:\\cygwin64'
        key: ${{ runner.os }}-cygwin
        restore-keys: |
          ${{ runner.os }}-cygwin
    - name: AQA
      uses: sophia-guo/run-aqa@checkif
      with: 
        version: '11'
        jdksource: 'github-hosted'
        build_list: 'openjdk'
        target: '_jdk_custom'
