name: "run-aqa build with push to master"
on:
  push:


jobs:
  test: # 
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest] #[ubuntu-latest, macos-latest, windows-2016]
    steps:
    - uses: actions/checkout@v1
    - run: gcc -v