name: "run-aqa action tests"
on:
  push:

jobs:
  hotspot16:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        version: [8]
        impl: [hotspot]
        buildlist: [openjdk]
    steps:
    - uses: actions/checkout@v1
    - uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: ${{ matrix.version }}
        targets: JDK_${{ matrix.version }}
        source: 'https://api.adoptopenjdk.net/v3/binary/latest/16/ea/linux/x64/jdk/openj9/normal/adoptopenjdk'
        archiveExtension: '.tar'

 