name: "run-aqa build with push to master"
on:
  push:


jobs:
  installJDK: # make sure build/ci work properly
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]#[ubuntu-latest, macos-latest, windows-2016]
    steps:
    - uses: actions/checkout@v1
    - uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: '8'
        targets: 'JDK_8'
        #impl: 'openj9'
        source: 'https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u-2020-12-02-12-32/OpenJDK8U-jdk_x64_linux_hotspot_2020-12-02-12-32.tar.gz'
        sourceType: 'url'
        
    - name: AQA
      uses:  AdoptOpenJDK/run-aqa@v1
      with: 
        version: '8'
        jdksource: 'install-jdk'
        build_list: 'openjdk'
        target: '_jdk_custom'
        custom_target: 'jdk/test/java/util/concurrent/forkjoin/AccessControlContext.java'