name: "nightly build-jdk nightly"
on:
  push:

jobs:
  hotspot14:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, macos-10.15]
    steps:
    - uses: actions/checkout@v2
    - run: printenv
 