name: "build-test"
on: # rebuild any PRs and main branch changes
  push:
jobs:
  build: # make sure build/ci work properly
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: AdoptOpenJDK/run-aqa@v1
      with:
        version: '11'
        build_list: 'openjdk'
        target: '_jdk_custom'
      shell: bash