name: "nightly build-jdk nightly"
on:
  push:

jobs:
  hotspot14:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, macos-10.15, windows-2016]
    steps:
    - uses: actions/checkout@v2
    - uses: AdoptOpenJDK/build-jdk@v1
      id: buildJDK
      with: 
        javaToBuild: 'jdk14u'
    - run: ${{ steps.buildJDK.outputs.BuildJDKDir }}/bin/java -version
  
