name: "place holder for example"
on:
  push:
    # branches-ignore:
    #   - '**'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2016] #[ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: ./
    - uses: sophia-guo/run-aqa@checkif
      id: buildJDK
      with: 
        version: '11'
        build_list: 'openjdk'
        target: '_jdk_math'
        git jdksource: 'github-hosted'