name: "run-aqa build with push to master"
on:
  push:


jobs:
  test: # 
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04] #[ubuntu-latest, macos-latest, windows-2016]
        version: [11]
    steps:
    - uses: actions/checkout@v1
    - uses: sophia-guo/build-openj9@jdk11
      id: buildJDK
      with: 
        version: ${{ matrix.version }}
    - run: ${{ steps.buildJDK.outputs.BuildJDKDir }}/bin/java -version