name: "Mac, openj9, jdk8"
on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, macos-10.15]
    steps:
    - uses: sophia-guo/build-jdk-openj9@mac
      id: buildJDK
      with: 
        version: '11'
    - run: ${{ steps.buildJDK.outputs.BuildJDKDir }}/bin/java -version
    - uses: actions/upload-artifact@v2-preview
      with:
        name: JDK
        path: ./**/artifacts/*.tar.gz/