name: build
on: push

jobs:
  hotspot:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: '11'
        targets: 'JDK_11'
    - name: AQA
      uses: adoptium/run-aqa@master
      with: 
        version: '11'
        jdksource: 'customized'
        build_list: 'system'
        target: '_system_custom'
        aqa-testsRepo: xius666/aqa-tests:issue2949
        aqa-systemtestsRepo: sophia-guo/aqa-systemtest:stf
