name: "place holder for example"
on:
  pull_request:
    branches-ignore:
      - '**'
jobs:
  build:
    runs-on: ubuntu-16.04 # ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - uses: ./
    - run: printenv
