name: "place holder for example"
on:
  push:
#    branches-ignore:
#      - '**'
jobs:
  build:
    runs-on: windows-2016 # ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - uses: ./
    - run: printenv