name: "nightly build-jdk nightly"
on:
  push:

jobs:
  hotspot16:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, macos-10.15, windows-2016]
        javaToBuild: [jdk16]
    steps:
    - uses: actions/checkout@v1
    - uses: sophia-guo/build-jdk@version
      id: buildJDK
      with: 
        javaToBuild: ${{ matrix.javaToBuild }}
    - run: ${{ steps.buildJDK.outputs.BuildJDKDir }}/bin/java -version
